# Generated by Django 4.2.11 on 2024-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
