# Generated by Django 4.2.11 on 2024-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometools', '0002_productdetails_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='des',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
