# Generated by Django 4.2.11 on 2024-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_cart_alter_itemdetails_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
