# Generated by Django 4.2.11 on 2024-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_itemdetails_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='des',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
